FROM java:9
EXPOSE 8080
ADD /target/challenge-bravo.jar challenge-bravo.jar
ENTRYPOINT ["java", "-jar", "challenge-bravo.jar"]

### Created jar file ####
#### mvn clean install

### Create image ###
##  docker build -f DockerFile -t challenge-bravo .

### Run image ###
### docker run -p 8080:8080 --name challenge-bravo  challenge-bravo